# Generated by Django 2.2.7 on 2019-11-30 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
