# Generated by Django 2.2.7 on 2019-11-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_wallpaper_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallpaper',
            new_name='Picture',
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
